apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-demo-app.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "devops-demo-app.name" . }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
